### PR TITLE
add exif.d.ts

### PR DESCRIPTION
**Pull request by intasect**
We want use this library in our TypeScript project, so I add a exif.d.ts to make it can import into TypeScript.

### CODE REVIEW

**Comment by ivanmayes** [comment]
+1

**Comment by codeandcats** [comment]
***bump***

**Comment by bartvanderwal** [comment]
Thanks!
I merged. 
Had some small doubts, like shouldn't you put this in the definitelytyped repo instead? But it's been a while since I used Typescript. And it seems now 'typings' is the thing to use. Does this conform to their way of working? Shouldn't there be a typings folder or typings.json or something?

**Comment by codeandcats** [comment]
Hey @bartvanderwal, yes sorry I should have looked closer at this commit. Indeed the file should either be called index.d.ts _or_ there should be a "types" or "typings" property in the package.json that points to the .d.ts file.

More on [publishing typings](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

**Pull request merged**
